### ISSUE TITLE
Ganache Metamask RPC error

### ISSUE THREAD

**Issue by billtlee** [Ben-Haslam/Alternative-Uniswap-Interface#21]
Hi,

Thanks for this cool repo!  I am playing with this using Ganache.  I deployed 2 tokens, factory, router and weth contracts.  I am trying to add liquidity but ran into an RPC error.  Has anyone run into the same issue?  Thanks in advance!

MetaMask - RPC Error: Internal JSON RPC error. code: -21603

**Comment by billtlee** [comment]
I also tried it on Rinkeby as well and am getting MetaMask RPC Error -32000, unable to estimate gas.

**Comment by PhilCrossx** [comment]
Kindly send a report of your issue to metadappsupport@gmail.com

**Comment by billtlee** [comment]
Thanks for getting back!  I finally managed to get it to work.  I think it had to do with the contracts.  However, I don't know why.  I just forked the unswap moonbase contracts and those seem to work perfectly with your interface.

**Comment by Ben-Haslam** [comment]
OK interesting, glad you sorted it. I also managed to deploy some contracts to Ganache which then worked fine, so will close this issue for now. The script and contracts I used to deploy are here: 
https://github.com/Ben-Haslam/uniswap-deploy-scripts
